/*
* To change this license header, choose License Headers in Project Properties.
* To change this template file, choose Tools | Templates
* and open the template in the editor.
*/
package schoolmanagementsystem;

import java.awt.Color;
import java.awt.HeadlessException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
//import java.awt.Toolkit;
import javax.swing.JPanel;
import javax.swing.jOptionPane;

/**
 *
 * @author Administrator
 */
public class StudentProfile extends javax.swing.JFrame {
    
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st;
    public String id;
    public StudentProfile() {
        this.setUndecorated(true);
        initComponents();
        hideSideMenu();
    }
    public StudentProfile(String id) {
        this.setUndecorated(true);
        initComponents();
        hideSideMenu();
        conn = JConnection.connectdb();
        this.id=id;  
        profileShow();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        close_btn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        HomePanel = new javax.swing.JPanel();
        NameFDB = new javax.swing.JLabel();
        SectionText = new javax.swing.JLabel();
        SectionFDB = new javax.swing.JLabel();
        NameText2 = new javax.swing.JLabel();
        IDTest1 = new javax.swing.JLabel();
        IDFDB = new javax.swing.JLabel();
        HomeworkPanel = new javax.swing.JPanel();
        HomeworkPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        AttendencePanel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        noticePanel = new javax.swing.JPanel();
        HomeworkPanel2 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        N_ID = new javax.swing.JTextArea();
        resultPanel = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        sideMenu = new javax.swing.JPanel();
        home_btn = new javax.swing.JPanel();
        ind_0 = new javax.swing.JPanel();
        Home1 = new javax.swing.JLabel();
        homework_btn = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        Homework = new javax.swing.JLabel();
        result_btn = new javax.swing.JPanel();
        ind_2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        attendance_btn = new javax.swing.JPanel();
        ind_4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        logOut = new javax.swing.JButton();
        notices_btn = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        sideMenuHide = new javax.swing.JLabel();
        MenuText = new javax.swing.JLabel();
        SideMenuShow = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(19, 10, 52));

        close_btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schoolmanagementsystem/image/close.png"))); // NOI18N
        close_btn.setBorder(null);
        close_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        close_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                close_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1250, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(close_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 32));

        HomePanel.setBackground(new java.awt.Color(65, 59, 94));

        NameFDB.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        NameFDB.setForeground(new java.awt.Color(51, 255, 255));
        NameFDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameFDB.setText("Name Show");

        SectionText.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        SectionText.setForeground(new java.awt.Color(255, 255, 255));
        SectionText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SectionText.setText("Section");

        SectionFDB.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        SectionFDB.setForeground(new java.awt.Color(153, 255, 255));
        SectionFDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SectionFDB.setText("Section show");

        NameText2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        NameText2.setForeground(new java.awt.Color(255, 255, 255));
        NameText2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameText2.setText("Name");

        IDTest1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        IDTest1.setForeground(new java.awt.Color(255, 255, 255));
        IDTest1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDTest1.setText("ID");

        IDFDB.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        IDFDB.setForeground(new java.awt.Color(153, 255, 255));
        IDFDB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDFDB.setText("ID show");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(NameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(IDTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(IDFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(HomePanelLayout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(NameFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(559, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SectionText, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(SectionFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(574, 574, 574))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomePanelLayout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NameText2, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IDTest1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IDFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SectionText, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SectionFDB, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(237, 237, 237))
        );

        jTabbedPane1.addTab("home", HomePanel);

        HomeworkPanel1.setBackground(new java.awt.Color(65, 59, 94));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("HomeWork");

        jTextPane1.setEditable(false);
        jScrollPane2.setViewportView(jTextPane1);

        javax.swing.GroupLayout HomeworkPanel1Layout = new javax.swing.GroupLayout(HomeworkPanel1);
        HomeworkPanel1.setLayout(HomeworkPanel1Layout);
        HomeworkPanel1Layout.setHorizontalGroup(
            HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 854, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(152, Short.MAX_VALUE))
        );
        HomeworkPanel1Layout.setVerticalGroup(
            HomeworkPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 442, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout HomeworkPanelLayout = new javax.swing.GroupLayout(HomeworkPanel);
        HomeworkPanel.setLayout(HomeworkPanelLayout);
        HomeworkPanelLayout.setHorizontalGroup(
            HomeworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1035, Short.MAX_VALUE)
            .addGroup(HomeworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeworkPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(HomeworkPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        HomeworkPanelLayout.setVerticalGroup(
            HomeworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 683, Short.MAX_VALUE)
            .addGroup(HomeworkPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(HomeworkPanelLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(HomeworkPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("homework", HomeworkPanel);

        jLabel10.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel10.setText("Attendance");

        javax.swing.GroupLayout AttendencePanelLayout = new javax.swing.GroupLayout(AttendencePanel);
        AttendencePanel.setLayout(AttendencePanelLayout);
        AttendencePanelLayout.setHorizontalGroup(
            AttendencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendencePanelLayout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel10)
                .addContainerGap(612, Short.MAX_VALUE))
        );
        AttendencePanelLayout.setVerticalGroup(
            AttendencePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AttendencePanelLayout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addGap(386, 386, 386))
        );

        jTabbedPane1.addTab("attendence", AttendencePanel);

        HomeworkPanel2.setBackground(new java.awt.Color(65, 59, 94));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 1, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Notice");

        jLabel16.setBackground(new java.awt.Color(65, 59, 94));
        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Notice");

        jScrollPane3.setBackground(new java.awt.Color(18, 30, 49));
        jScrollPane3.setForeground(new java.awt.Color(255, 255, 255));

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jTextArea2.setRows(5);
        jTextArea2.setCaretColor(new java.awt.Color(18, 30, 49));
        jScrollPane3.setViewportView(jTextArea2);

        jLabel17.setBackground(new java.awt.Color(65, 59, 94));
        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Message:");

        jScrollPane4.setBackground(new java.awt.Color(18, 30, 49));
        jScrollPane4.setForeground(new java.awt.Color(255, 255, 255));

        N_ID.setEditable(false);
        N_ID.setColumns(20);
        N_ID.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        N_ID.setRows(5);
        N_ID.setCaretColor(new java.awt.Color(18, 30, 49));
        jScrollPane4.setViewportView(N_ID);

        javax.swing.GroupLayout HomeworkPanel2Layout = new javax.swing.GroupLayout(HomeworkPanel2);
        HomeworkPanel2.setLayout(HomeworkPanel2Layout);
        HomeworkPanel2Layout.setHorizontalGroup(
            HomeworkPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(HomeworkPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 953, Short.MAX_VALUE)
                    .addComponent(jScrollPane3)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        HomeworkPanel2Layout.setVerticalGroup(
            HomeworkPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeworkPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout noticePanelLayout = new javax.swing.GroupLayout(noticePanel);
        noticePanel.setLayout(noticePanelLayout);
        noticePanelLayout.setHorizontalGroup(
            noticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, noticePanelLayout.createSequentialGroup()
                .addComponent(HomeworkPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        noticePanelLayout.setVerticalGroup(
            noticePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(noticePanelLayout.createSequentialGroup()
                .addComponent(HomeworkPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("notice", noticePanel);

        jLabel12.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel12.setText("Result");

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(290, 290, 290)
                .addComponent(jLabel12)
                .addContainerGap(675, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addGap(291, 291, 291)
                .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(368, 368, 368))
        );

        jTabbedPane1.addTab("result", resultPanel);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 1040, 710));

        sideMenu.setBackground(new java.awt.Color(19, 10, 52));

        home_btn.setBackground(new java.awt.Color(65, 59, 94));
        home_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                home_btnMousePressed(evt);
            }
        });

        ind_0.setBackground(new java.awt.Color(255, 255, 255));
        ind_0.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_0Layout = new javax.swing.GroupLayout(ind_0);
        ind_0.setLayout(ind_0Layout);
        ind_0Layout.setHorizontalGroup(
            ind_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_0Layout.setVerticalGroup(
            ind_0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 82, Short.MAX_VALUE)
        );

        Home1.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Home1.setForeground(new java.awt.Color(255, 255, 255));
        Home1.setText("Home");

        javax.swing.GroupLayout home_btnLayout = new javax.swing.GroupLayout(home_btn);
        home_btn.setLayout(home_btnLayout);
        home_btnLayout.setHorizontalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(home_btnLayout.createSequentialGroup()
                .addComponent(ind_0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, home_btnLayout.createSequentialGroup()
                    .addContainerGap(58, Short.MAX_VALUE)
                    .addComponent(Home1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(47, 47, 47)))
        );
        home_btnLayout.setVerticalGroup(
            home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_0, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
            .addGroup(home_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(home_btnLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(Home1, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        homework_btn.setBackground(new java.awt.Color(19, 10, 52));
        homework_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homework_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                homework_btnMousePressed(evt);
            }
        });

        ind_1.setBackground(new java.awt.Color(255, 255, 255));
        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        Homework.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        Homework.setForeground(new java.awt.Color(255, 255, 255));
        Homework.setText("Homework");

        javax.swing.GroupLayout homework_btnLayout = new javax.swing.GroupLayout(homework_btn);
        homework_btn.setLayout(homework_btnLayout);
        homework_btnLayout.setHorizontalGroup(
            homework_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homework_btnLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(Homework)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        homework_btnLayout.setVerticalGroup(
            homework_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
            .addComponent(Homework, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        result_btn.setBackground(new java.awt.Color(19, 10, 52));
        result_btn.setForeground(new java.awt.Color(255, 255, 255));
        result_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        result_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                result_btnMousePressed(evt);
            }
        });

        ind_2.setBackground(new java.awt.Color(255, 255, 255));
        ind_2.setOpaque(false);
        ind_2.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_2Layout = new javax.swing.GroupLayout(ind_2);
        ind_2.setLayout(ind_2Layout);
        ind_2Layout.setHorizontalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_2Layout.setVerticalGroup(
            ind_2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Result");

        javax.swing.GroupLayout result_btnLayout = new javax.swing.GroupLayout(result_btn);
        result_btn.setLayout(result_btnLayout);
        result_btnLayout.setHorizontalGroup(
            result_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(result_btnLayout.createSequentialGroup()
                .addComponent(ind_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        result_btnLayout.setVerticalGroup(
            result_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        attendance_btn.setBackground(new java.awt.Color(19, 10, 52));
        attendance_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        attendance_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                attendance_btnMousePressed(evt);
            }
        });

        ind_4.setBackground(new java.awt.Color(255, 255, 255));
        ind_4.setOpaque(false);
        ind_4.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_4Layout = new javax.swing.GroupLayout(ind_4);
        ind_4.setLayout(ind_4Layout);
        ind_4Layout.setHorizontalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_4Layout.setVerticalGroup(
            ind_4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Attendance");

        javax.swing.GroupLayout attendance_btnLayout = new javax.swing.GroupLayout(attendance_btn);
        attendance_btn.setLayout(attendance_btnLayout);
        attendance_btnLayout.setHorizontalGroup(
            attendance_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(attendance_btnLayout.createSequentialGroup()
                .addComponent(ind_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel3)
                .addGap(0, 68, Short.MAX_VALUE))
        );
        attendance_btnLayout.setVerticalGroup(
            attendance_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
            .addComponent(ind_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        logOut.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        logOut.setForeground(new java.awt.Color(255, 255, 255));
        logOut.setText("LogOut");
        logOut.setBorder(null);
        logOut.setBorderPainted(false);
        logOut.setContentAreaFilled(false);
        logOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });

        notices_btn.setBackground(new java.awt.Color(19, 10, 52));
        notices_btn.setForeground(new java.awt.Color(255, 255, 255));
        notices_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notices_btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notices_btnMousePressed(evt);
            }
        });

        ind_3.setBackground(new java.awt.Color(255, 255, 255));
        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(5, 60));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Notices");

        javax.swing.GroupLayout notices_btnLayout = new javax.swing.GroupLayout(notices_btn);
        notices_btn.setLayout(notices_btnLayout);
        notices_btnLayout.setHorizontalGroup(
            notices_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(notices_btnLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        notices_btnLayout.setVerticalGroup(
            notices_btnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ind_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        sideMenuHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu.jpg"))); // NOI18N
        sideMenuHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sideMenuHideMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout sideMenuLayout = new javax.swing.GroupLayout(sideMenu);
        sideMenu.setLayout(sideMenuLayout);
        sideMenuLayout.setHorizontalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(logOut)
                .addGap(25, 25, 25))
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideMenuHide)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(attendance_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notices_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(home_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(homework_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(result_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideMenuLayout.setVerticalGroup(
            sideMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(sideMenuHide)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(home_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(homework_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(attendance_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(notices_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(result_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addComponent(logOut, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        jPanel1.add(sideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 240, 690));

        MenuText.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        MenuText.setText("Menu");
        jPanel1.add(MenuText, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 90, 60));

        SideMenuShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu.jpg"))); // NOI18N
        SideMenuShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SideMenuShowMouseClicked(evt);
            }
        });
        jPanel1.add(SideMenuShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 42, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    int x =242;
    public void hideSideMenu(){
        if(x==242)
        {
	sideMenu.setSize(242,720);
	Thread th = new Thread(){
		@Override
		public void run(){
			try{
				for(int i = 242;i>=0;i=i-11){
					Thread.sleep(1);
					sideMenu.setSize(i,720);
				}
			}catch(Exception e){
				jOptionPane.showMessegeDialog(null,e);
                        }  
                }
		};th.start();
	x=0;
        }
    }

    public void profileShow(){
        final JPanel panel = new JPanel();
            String student_id ="100.17";
            try{
                
                String sql = "SELECT name, class, sec, id, pass FROM student_accounts WHERE id='" + student_id + "' ";
                try{
                st = (Statement) conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_READ_ONLY);
                rs = st.executeQuery(sql);
                if (rs.next()) {
                    String StudentName = rs.getString("name");
                    String ID = rs.getString("id");
                    String Section = rs.getString("sec");
                    NameFDB.setText(StudentName);
                    IDFDB.setText(ID);
                    SectionFDB.setText(Section);
                    
                }else{
                    JOptionPane.showMessageDialog(null, "Sorry,No data found for this ID","Student ID",JOptionPane.ERROR_MESSAGE);
                     JOptionPane.showMessageDialog(null, "Enter valid  ID","Student ID",JOptionPane.INFORMATION_MESSAGE);
                }
            
                }catch(HeadlessException | SQLException e){
                JOptionPane.showMessageDialog(panel, "Database error. Auto login failed.","Warning",JOptionPane.WARNING_MESSAGE);
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(panel, "SQL Syntax WRONG","Database",JOptionPane.ERROR_MESSAGE);
            }
            
            
    }
    private void home_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
        setColor(home_btn);
        // resetColor(new JPanel[](homework_btn;result_btn;notices_btn;attendance_btn));
        resetColor(homework_btn);
        resetColor(result_btn);
        resetColor(notices_btn);
        resetColor(attendance_btn);
        
        ind_0.setOpaque(true);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        
        
    }//GEN-LAST:event_home_btnMousePressed

    private void homework_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homework_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(1);
        setColor(homework_btn);
        // resetColor(new JPanel[](homework_btn;result_btn;notices_btn;attendance_btn));
        resetColor(home_btn);
        resetColor(result_btn);
        resetColor(notices_btn);
        resetColor(attendance_btn);
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(true);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        
        
    }//GEN-LAST:event_homework_btnMousePressed

    private void result_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_result_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
        setColor(result_btn);
        // resetColor(new JPanel[](homework_btn;result_btn;notices_btn;attendance_btn));
        resetColor(homework_btn);
        resetColor(home_btn);
        resetColor(notices_btn);
        resetColor(attendance_btn);
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(false);
        ind_2.setOpaque(true);
        ind_3.setOpaque(false);
        ind_4.setOpaque(false);
        
    }//GEN-LAST:event_result_btnMousePressed

    private void notices_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notices_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
        setColor(notices_btn);
        // resetColor(new JPanel[](homework_btn;result_btn;notices_btn;attendance_btn));
        resetColor(homework_btn);
        resetColor(result_btn);
        resetColor(home_btn);
        resetColor(attendance_btn);
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(true);
        ind_4.setOpaque(false);
        
        
    }//GEN-LAST:event_notices_btnMousePressed

    private void attendance_btnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_attendance_btnMousePressed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
        setColor(attendance_btn);
        // resetColor(new JPanel[](homework_btn;result_btn;notices_btn;attendance_btn));
        resetColor(homework_btn);
        resetColor(result_btn);
        resetColor(notices_btn);
        resetColor(home_btn);
        
        ind_0.setOpaque(false);
        ind_1.setOpaque(false);
        ind_2.setOpaque(false);
        ind_3.setOpaque(false);
        ind_4.setOpaque(true);
        
        
    }//GEN-LAST:event_attendance_btnMousePressed

    private void close_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_close_btnActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_close_btnActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        final JPanel panel = new JPanel();
        try {
            InetAddress myIP=InetAddress.getLocalHost();
            PreparedStatement  preparedStatement = conn.prepareStatement("update login_info set state =?  where id = \'"+id+"\' and ip_address=\'"+myIP.getHostAddress()+"\'");
            preparedStatement.setInt(1, 0);
            int update_done = preparedStatement.executeUpdate();
            logInPage LP= new logInPage();
            LP.setVisible(true);
            LP.setResizable(false);
            dispose();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(panel, "Database error","Warning",JOptionPane.WARNING_MESSAGE);
            
        } catch (UnknownHostException ex) {
            JOptionPane.showMessageDialog(panel, "Sorry, Can't get your IP Address.","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_logOutActionPerformed
    
    private void sideMenuHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sideMenuHideMouseClicked
        if(x==242)
        {
            sideMenu.setSize(242,720);
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i = 242;i>=0;i--){
                            Thread.sleep(1);
                            sideMenu.setSize(i,720);
                        }
                    }catch(Exception e){
                        jOptionPane.showMessegeDialog(null,e);
                    }
                }
            };th.start();
            x=0;
        }
    }//GEN-LAST:event_sideMenuHideMouseClicked

    private void SideMenuShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SideMenuShowMouseClicked
        if(x == 0)
        {
            sideMenu.show();
            jTabbedPane1.show();
            //jTabbedPane2.show();
            sideMenu.setSize(242,720);//[418, 720]
            Thread th = new Thread(){
                @Override
                public void run(){
                    try{
                        for(int i = 0; i <= x; i++){
                            Thread.sleep(1);
                            sideMenu.setSize(i,720);
                        }
                    }catch(Exception e){
                        jOptionPane.showMessegeDialog(null,e);
                    }
                }
            };th.start();
            x=242;
        }
    }//GEN-LAST:event_SideMenuShowMouseClicked
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
        * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentProfile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentProfile().setVisible(true);
            }
        });
    }
    
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(65,59,94));
    }
    
    
    private void resetColor(JPanel pane)
    {
        //for(int i=0;i<pane.length;i++)
        // {
        pane.setBackground(new Color(19,10,52));
        // }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AttendencePanel;
    private javax.swing.JLabel Home1;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel Homework;
    private javax.swing.JPanel HomeworkPanel;
    private javax.swing.JPanel HomeworkPanel1;
    private javax.swing.JPanel HomeworkPanel2;
    private javax.swing.JLabel IDFDB;
    private javax.swing.JLabel IDTest1;
    private javax.swing.JLabel MenuText;
    private javax.swing.JTextArea N_ID;
    private javax.swing.JLabel NameFDB;
    private javax.swing.JLabel NameText2;
    private javax.swing.JLabel SectionFDB;
    private javax.swing.JLabel SectionText;
    private javax.swing.JLabel SideMenuShow;
    private javax.swing.JPanel attendance_btn;
    private javax.swing.JButton close_btn;
    private javax.swing.JPanel home_btn;
    private javax.swing.JPanel homework_btn;
    private javax.swing.JPanel ind_0;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_2;
    private javax.swing.JPanel ind_3;
    private javax.swing.JPanel ind_4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JButton logOut;
    private javax.swing.JPanel noticePanel;
    private javax.swing.JPanel notices_btn;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel result_btn;
    private javax.swing.JPanel sideMenu;
    private javax.swing.JLabel sideMenuHide;
    // End of variables declaration//GEN-END:variables
}
